config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  resources :users, only:[:show, :edit, :update, :destroy, :confirm, :followers, :following, :matching] do
    member do
      get :confirm, :following, :followers, :matching
    end
  end

  root 'statics#top'
  get 'statics/about'
  get 'statics/borrow'
  get 'statics/lend'
  resources :statics, only:[:top, :about, :borrow, :lend]

  resources :houses do
    member do
      get :confirm
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :chats, only:[:show] do
    collection do
      get :show
    end
  end

  resources :rooms, only:[:index, :create] do
    resources :talks, only:[:index, :create]
  end

  mount ActionCable.server => '/cable'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :houses, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :talks, dependent: :destroy


  attachment :user_image

  enum which: { "借りる": 0, "貸したい": 1 }
  enum sex: { "男": 0, "女": 1 }
  # 都道府県を選択できる
  enum prefecture: {
    お住まいの都道府県を選択して下さい:0,
    北海道:1, 青森県:2, 岩手県:3, 宮城県:4, 秋田県:5, 山形県:6, 福島県:7, 茨城県:8,
    栃木県:9, 群馬県:10, 埼玉県:11, 千葉県:12, 東京都:13, 神奈川県:14, 新潟県:15, 富山県:16,
    石川県:17, 福井県:18, 山梨県:19, 長野県:20, 岐阜県:21, 静岡県:22, 愛知県:23, 三重県:24,
    滋賀県:25, 京都府:26, 大阪府:27, 兵庫県:28, 奈良県:29, 和歌山県:30, 鳥取県:31, 島根県:32,
    岡山県:33, 広島県:34, 山口県:35, 徳島県:36, 香川県:37, 愛媛県:38, 高知県:39,
    福岡県:40, 佐賀県:41, 長崎県:42, 熊本県:43, 大分県:44, 宮崎県:45, 鹿児島県:46, 沖縄県:47
  }

  validates :name, presence: true
  validates :introduction, presence: true
  validates :which, presence: true
  validates :sex, presence: true
  validates :prefecture, presence: true

  # フォローしているか確認
  def following?(other_user)
    following.include?(other_user)
  end

  # フォローされているか確認
  def followers?(other_user)
    followers.include?(other_user)
  end

  # マッチングしているか確認
  def matching?(other_user)
    matching.include?(other_user)
  end

  # フォローする
  def follow(other_user)
    following << other_user
  end

  # アンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # マッチング
  def matching
    following & followers
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  PER = 10
 
 
  def show
    @user = User.find(params[:id])
    @relationship = Relationship.new
  end

  def confirm
    @user = User.find(params[:id])
    @house = House.where(user_id: current_user)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(PER).reverse_order
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(PER).reverse_order
  end

  def matching
    @user = User.find(params[:id])
    @users = current_user.matching
    # @users = @user.matching.page(params[:page]).per(PER).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to confirm_user_path(@user.id), notice: "プロフィールを更新しました。"
    else
      flash.now[:user] = "プロフィールの更新に失敗しました。全ての項目を入力して下さい。"
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "退会しました。ご利用ありがとうございました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :which, :sex, :prefecture, :user_image, :introduction, :email)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <% if current_user.following?(@user) %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), local: true, method: :delete, remote: true) do |like| %>
      <%= like.submit "いいね取り消し", class: "btn btn-danger userConfirmpage_btn4 form-control" %>
    <% end %>
  <% elsif current_user.followers?(@user) %>
    <%= form_with(model: current_user.active_relationships.build, remote: true, local: true) do |like| %>
      <%= hidden_field_tag :followed_id, @user.id %> 
      <%= like.submit "いいねありがとう", class: "btn userConfirmpage_btn5 form-control" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.build, remote: true, local: true) do |like| %>
      <%= hidden_field_tag :followed_id, @user.id %> 
      <%= like.submit "いいね", class: "btn btn-primary userConfirmpage_btn4 form-control" %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_info.html.erb
<% @user || current_user %>
<div class="userInfo">
  <%= link_to "いいねしている", following_user_path(@user) %>
  <strong><%= @user.following.count %></strong>  |

  <%= link_to "いいねされた", followers_user_path(@user) %>
  <strong><%= @user.followers.count %></strong>  |

  <%= link_to "マッチング済", matching_user_path(@user) %>
  <strong><%= @user.matching.count %></strong>
</div>

app/views/users/confirm.html.erb
<section class="userConfirmpage"> 
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="userConfirmpage_img text-center">
          <%= attachment_image_tag @user, :user_image, fallback: "no_image.jpg", size: "200x200" %>
        </div>

        <div class="userConfirmpage_info">
          <%= render 'users/info' %>
        </div>
        <hr class="divider light my-4">
       
        <% if flash[:notice] %>
          <p class="alertmessage">
            <%= flash[:notice] %>
          </p>
        <% end %>
        
        <div class="userConfirmpage_line">
          <div class="userConfirmpage_name">
            <i class="fas fa-user"></i> <%= @user.name %>
          </div>
        
          <div class="userConfirmpage_radio">
            性別：<%= @user.sex %>  |  <%= @user.which %>
          </div>

          <div class="userConfirmpage_radio">
            居住地：<%= @user.prefecture %>在住
          </div>

          <div class="userConfirmpage_radio">
            メールアドレス：<%= @user.email %>
          </div>

          <div class="userConfirmpage_introduction">
            <mark class="bg-info">自己紹介</mark><br><br>
            <%= @user.introduction %>
          </div>
        </div>
        <hr class="divider light my-4">

        <h3>
          <%= link_to "プロフィールを編集する", edit_user_path(@user), class: "btn userConfirmpage_btn" %>
        </h3>

        <div class="userConfirmpage_content">
          <p>
            1人暮らしの悩みや不安、情報等を皆で共有しよう！<br>
            <i class="fas fa-arrow-down"></i>
          </p>
        </div>

        <h3>
          <%= link_to "つぶやく", chats_path, class: "btn userConfirmpage_btn6" %>
        </h3>

        <table class="table table-striped">
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

          <% @house.each do |house| %>
            <tr>
              <td><%= attachment_image_tag house, :house_image, fallback: "no_house_image.jpg", size: "50x50" %></td>
              <td><%= house.title %></td>
              <td><%= house.prefecture %></td>
              <td><%= link_to "詳細", confirm_house_path(house.id), class: "btn btn-sm userConfirmpage_btn2" %></td>
            </tr>
          <% end %>
        </table>

      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="userEditpage"> 
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-1"></div>
      <div class="col-md-6">
        <h2 class="userEditpage_title">プロフィール編集</h2>
        
        <p class="flashmessage">
          <%= flash.now[:user] %>
        </p>

        <div class="form-body">
          <%= form_with(model: @user, local: true) do |f| %>
            
            <div class="userEditpage_field">
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "名前（ニックネーム可）" %>
            </div>

            <div class="userEditpage_field">
              <div class="form-group">
                <div class="form-check form-check-inline">
                  <%= f.radio_button :which, "借りる", class: "form-check-input", id: "whichRadio1" %>
                  <label class="form-check-label" for="whichRadio1">借りる</label>
                </div>
                <div class="form-check form-check-inline">
                  <%= f.radio_button :which, "貸したい", class: "form-check-input", id: "whichRadio2" %>
                  <label class="form-check-label" for="whichRadio2">貸したい</label>
                </div>
              </div>
            </div>

            <div class="userEditpage_field">
              <div class="form-group">
                <div class="form-check form-check-inline">
                  <%= f.radio_button :sex, "男", class: "form-check-input", id: "sexRadio1" %>
                  <label class="form-check-label" for="sexRadio1">男</label>
                </div>
                <div class="form-check form-check-inline">
                  <%= f.radio_button :sex, "女", class: "form-check-input", id: "sexRadio2" %>
                  <label class="form-check-label" for="sexRadio2">女</label>
                </div>
              </div>
            </div>

            <div class="uesrEditpage_field">
              <%= f.select :prefecture, User.prefectures.keys, {}, class: "form-control btn btn-info" %>
            </div>

            <div class="userEditpage_field">
              <label for="file_photo" class="rounded-circle userProfileImg">
                <div class="userProfileImg_description">プロフィール画像</div>
                <i class="fas fa-camera fa-3x"></i>
                <%= f.attachment_field :user_image, fallback: "no_image.jpg", id: "file_photo" %>
              </label>
            </div>

            <div class="userEditpage_field">
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "メールアドレス" %>
            </div>

            <div class="userEditpage_field">
              <%= f.text_area :introduction, maxlength: "500", rows: "10", autofocus: true, class: "form-control", placeholder: "自己紹介（１０文字以上５００文字以内）" %>
            </div>

            <div class="actions">
              <h3>
                <%= f.submit "プロフィールを更新する", class: "btn btn-success userEditpage_btn form-control" %>
              </h3>
            </div>
          <% end %>
        </div>
        
        <p class="userEditpage_destroy">
          ※ 退会すると登録したデータが全て消えてしまいます。
        </p>
        <h3>
          <%= link_to "退会する", user_path(@user.id), method: :delete, class: "btn btn-danger userEditpage_btn1 form-control", "data-confirm" => "退会すると【あなたの情報が全て失われてしまいます】がよろしいですか？" %>
        </h3>
      </div>

      <div class="col-md-1"></div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

app/views/users/followers.html.erb
<section class="userFollowpage">
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-1"></div>
      <div class="col-md-6">
        <h2 class="userFollowpage_title">いいねもらった相手</h2>

        <table class="table table-striped">
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>

          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :user_image, fallback: "no_image.jpg", size: "50x50" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "詳細", user_path(user.id), class: "btn btn-sm userFollowpage_btn" %></td>
            </tr>
          <% end %>
        </table>

        <h3 class="text-center">
          <%= paginate @users %>
        </h3>
      
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

app/views/users/following.html.erb
<section class="userFollowpage">
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-1"></div>
      <div class="col-md-6">
        <h2 class="userFollowpage_title">いいねしている相手</h2>

        <table class="table table-striped">
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>

          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :user_image, fallback: "no_image.jpg", size: "50x50" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "詳細", user_path(user.id), class: "btn btn-sm userFollowpage_btn" %></td>
            </tr>
          <% end %>
        </table>

        <h3 class="text-center">
          <%= paginate @users %>
        </h3>
      
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

app/views/users/matching.html.erb
<section class="userFollowpage">
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-1"></div>
      <div class="col-md-6">
        <h2 class="userFollowpage_title">マッチング済み</h2>

        <table class="table table-striped">
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>

          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :user_image, fallback: "no_image.jpg", size: "50x50" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "詳細", user_path(user.id), class: "btn btn-sm userFollowpage_btn" %></td>
            </tr>
          <% end %>
        </table>

      </div>
      <div class="col-md-1"></div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="userConfirmpage"> 
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="userConfirmpage_img text-center">
          <%= attachment_image_tag @user, :user_image, fallback: "no_image.jpg", size: "200x200" %>
        </div>
        <hr class="divider light my-4">
        
        <% if flash[:notice] %>
          <p class="alertmessage">
            <%= flash[:notice] %>
          </p>
        <% end %>
        
        <div class="userConfirmpage_line">
          <div class="userConfirmpage_name">
            <i class="fas fa-user"></i> <%= @user.name %>
          </div>
        
          <div class="userConfirmpage_radio">
            性別：<%= @user.sex %>  |  <%= @user.which %>
          </div>

          <div class="userConfirmpage_radio">
            居住地：<%= @user.prefecture %>在住
          </div>

          <div class="userConfirmpage_radio">
            メールアドレス：<%= @user.email %>
          </div>

          <div class="userConfirmpage_introduction">
            <mark class="bg-info">自己紹介</mark><br><br>
            <%= @user.introduction %>
          </div>
        </div>
        <hr class="divider light my-4">

        <% if user_signed_in? && current_user.id != @user.id %>
          <%= render 'users/follow_form' %>
        <% end %>

        <% if user_signed_in? && current_user.matching?(@user) %>
          <%= link_to "メッセージを送る", rooms_path(to_id: current_user.id, from_id: @user.id), method: :post, class: "btn userConfirmpage_btn5" %>
        <% end %>

      </div>
    </div>
  </div>
</section>