config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  resources :users, only:[:show, :edit, :update, :destroy, :confirm, :followers, :following, :matching] do
    member do
      get :confirm, :following, :followers, :matching
    end
  end

  root 'statics#top'
  get 'statics/about'
  get 'statics/borrow'
  get 'statics/lend'
  resources :statics, only:[:top, :about, :borrow, :lend]

  resources :houses do
    member do
      get :confirm
    end
  end

  resources :relationships, only:[:create, :destroy]

  resources :chats, only:[:show] do
    collection do
      get :show
    end
  end

  resources :rooms, only:[:index, :create] do
    resources :talks, only:[:index, :create]
  end

  mount ActionCable.server => '/cable'


end

app/views/layouts/_footer.html.erb
<footer>
  <small class="footer">
  <nav>
    <p class="button">
      <%= link_to "TOP", root_path %> | 
      <%= link_to "ABOUT", statics_about_path %>
    </p>
  </nav>
  </small>
  <div class="copyright">
    <p>Copyright (C) 2020 LivingAlone</p>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LivingAlone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# ナビゲーション %>
    <header class="navbar navbar-custom">
      <div class="container">
        <h3 class="logo">
          <%= link_to "LivingAlone", root_path %>
        </h3>

        <%# ログイン時 %>
        <% if user_signed_in? %>
        <nav>
          <ul class="nav navbar-expend-lg navbar-right">
            <li class= "livingAlone_header">
              <%= link_to "借りたい方", statics_borrow_path %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to "貸したい方", statics_lend_path %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to "住まいを探す", houses_path %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to current_user.name, confirm_user_path(current_user.id) %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </nav>

        <%# 非ログイン時 %>
        <% else %>
        <nav>
          <ul class="nav navbar-expand-lg navbar-right">
            <li class= "livingAlone_header">
              <%= link_to "ABOUT", statics_about_path %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to "住まいを探す", houses_path %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li class= "livingAlone_header">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
          </ul>
        </nav>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>